//
//  NodeAndViewControllerID.h
//  MessageFrame
//
//  Created by 95190 on 13-4-1.
//  Copyright (c) 2013年 95190. All rights reserved.
//

#ifndef MessageFrame_NodeAndViewControllerID_h
#define MessageFrame_NodeAndViewControllerID_h

#define NODE_WORK_LENGTH 100
//按模块划分，每个模块分配100个ID(ID不可为Node类型),作为本Node的工作范围，以NODE为当前根节点
enum NodeAndViewControllerID
{
    VIEWCONTROLLER_NONE = -3,
    NODE_NONE = -2,
    VIEWCONTROLLER_RETURN = -1,
    NODE_ROOT = 0,
    
    
    //SystemNode节点
    NODE_SYSTEM = 1000,
    VIEWCONTROLLER_LOGIN,
    //AppNode节点
    NODE_APP=1101,
    VIEWCONTROLLER_FEEDBACK,
  
    //GuideNode节点
    NODE_GUIDE=1201,
    VIEWCONTROLLER_GUIDE,
    
    
    //AppletNode节点
    NODE_APPLET=2000,
    VIEWCONTROLLER_HALL,
    //VehicleControlNode节点
    NODE_VEHICLECONTROL=2101,
    VIEWCONTROLLER_VEHICLECONTROL,
    VIEWCONTROLLER_VEHICLECONTROLHISTORY,
    VIEWCONTROLLER_VEHICLECONTROLHISTORYDETAIL,
    //VehicleConditionNode节点
    NODE_VEHICLECONDITION=2201,
    VIEWCONTROLLER_VEHICLECONDITION,
    VIEWCONTROLLER_VEHICLECONDITIONOFDOORORWINDOW,
    VIEWCONTROLLER_VEHICLECONDITIONOFBATTERY,
    
    //VehicleLocationNode节点
    NODE_VEHICLELOCATION=2601,
    VIEWCONTROLLER_VEHICLELOCATION,
    
    
    //UserMangerNode节点
    NODE_USERMANAGER=2301,
    VIEWCONTROLLER_USERMANAGEMENT ,
    VIEWCONTROLLER_USERINFO,
    VIEWCONTROLLER_USERMORE,
    VIEWCONTROLLER_USERABOUT,
    VIEWCONTROLLER_USERHELP,
    VIEWCONTROLLER_USERFEEDBACK,
    VIEWCONTROLLER_ABOUT,
    VIEWCONTROLLER_HELP,
    VIEWCONTROLLER_WELCOME,
    VIEWCONTROLLER_LOADING,
    VIEWCONTROLLER_PHONENUMBER,
    
    //UserinfoNode节点
    NODE_USERINFO=2401,
    VIEWCONTROLLER_UPDATEPHONE,
    VIEWCONTROLLER_CHANGEPASSWORD,
    //NotificationNewsNode节点
    NODE_NOTIFICATIONNEWS=1201,
    VIEWCONTROLLER_NOTIFICATIONNEWS,
    VIEWCONTROLLER_NOTIFICATIONNEWS_DETAIL,
    
    //Remotediagnosis Node节点
    NODE_REMOTEDIAGNOSIS=2501,
    VIEWCONTROLLER_DIAGNOSIS,


    NODE_TEST = 3000,
    VIEWCONTROLLER_TEST1,
    VIEWCONTROLLER_TEST2,
    VIEWCONTROLLER_TEST3,
};

#endif
